<?php

function cipher_menu() {
    $items['cipher'] = array(
        'title' => 'Shift Cipher',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('cipher_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['cipher_results_page'] = array(
        'title' => 'Results',
        'page callback' => 'cipher_results',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function cipher_form() {
    $form['shift_value'] = array(
        '#title' => 'Shift Value',
        '#type' => 'textfield',
        '#description' => 'Enter the number of places to shift each letter',
        '#required' => TRUE,
    );
    $form['shift_direction'] = array(
        '#title' => 'Shift Direction',
        '#type' => 'textfield',
        '#description' => 'Choose a direction to shift: right or left',
        '#required' => TRUE,
    );
    $form['text'] = array(
        '#title' => 'Text to Encrypt',
        '#type' => 'textfield',
        '#description' => 'Enter the text you would like to encrypt',
        '#required' => TRUE,
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Encrypt',
    );
    return $form;
}

function cipher_form_submit($form, &$form_state) {
    $form_state['redirect'] = 'cipher_results_page';
}

function cipher_results() {
    return 'Success!';
}
