<?php

function cipher_menu() {
    $items['cipher'] = array(
        'title' => 'Shift Cipher',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('cipher_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['cipher_results_page'] = array(
        'title' => 'Results',
        'page callback' => 'cipher_results',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function cipher_form() {
    $form['shift_value'] = array(
        '#title' => 'Shift Value',
        '#type' => 'textfield',
        '#description' => 'Enter the number of places to shift each letter',
        '#required' => TRUE,
        '#element_validate' => array('element_validate_integer_positive'),
    );
    $form['shift_direction'] = array(
        '#title' => 'Shift Direction',
        '#type' => 'textfield',
        '#description' => 'Choose a direction to shift: right or left',
        '#required' => TRUE,
        '#element_validate' => array('element_validate_shift_direction'),
    );
    $form['text'] = array(
        '#title' => 'Text to Encrypt',
        '#type' => 'textfield',
        '#description' => 'Enter the text you would like to encrypt',
        '#required' => TRUE,
        '#element_validate' => array('element_validate_invalid_characters'),
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Encrypt',
    );
    return $form;
}

function element_validate_shift_direction($element) {
    $direction = strtolower($element['#value']);
    if ($direction != 'right' && $direction != 'left') {
        form_error($element, t('Shift Direction must be "right" or "left"'));
    }
}

function element_validate_invalid_characters($element) {
    $valid_chars = array('a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z','.',',','?','!',' ');
    $text = strtolower($element['#value']);
    $inputted_chars = str_split($text);
    $invalid = false;
    foreach($inputted_chars as $char) {
        if (!in_array($char, $valid_chars)) {
            $invalid = true;
        }
    }
    if ($invalid == true) {
        form_error($element, t('You may only include alphabetical characters, spaces, and basic punctuation (. , ! ?)'));
    }
}

function cipher_form_submit($form, &$form_state) {
    $shift_value = $form_state['values']['shift_value'];
    $shift_direction = $form_state['values']['shift_direction'];
    $text = strtolower($form_state['values']['text']);
    $inputted_chars = str_split($text);
    $output = '';

    foreach($inputted_chars as $char) {
        if (ord($char) >= 97 && ord($char) <= 122) {
            if ($shift_direction == 'right') {
                $new_ascii = ord($char) + $shift_value;
            } else {
                $new_ascii = ord($char) - $shift_value;
            }
            while ($new_ascii > 122) {
                $new_ascii -= 26;
            }
            while ($new_ascii < 97) {
                $new_ascii += 26;
            }
            $output .= chr($new_ascii);
        } else {
            $output .= $char;
        }
    }
    $_SESSION['cipher'] = $output;
    $form_state['redirect'] = 'cipher_results_page';
}

function cipher_results() {
    return 'Success! Your cipher is: ' . $_SESSION['cipher'];
}
